import { Client, ProcedureCase } from '../../types.js';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-101',
    name: 'Cliente Empresa Demo S.A.',
    dniCuit: '30-00000000-1',
    type: 'PERSONA_JURIDICA',
    phone: '+54 11 0000-0000',
    email: 'empresa.demo@example.test',
    address: 'Calle Ficticia 123, CABA',
    notes: 'Cliente demo corporativo con flota ficticia.',
    casesCount: 2,
    createdAt: '2026-07-10',
  },
  {
    id: 'cli-102',
    name: 'Cliente Demo Persona',
    dniCuit: '20-00000002-4',
    phone: '+54 11 0000-0001',
    email: 'demo@example.test',
    type: 'PERSONA_HUMANA',
    address: 'Avenida Ejemplo 456, La Plata',
    notes: 'Trámite demo en proceso.',
    casesCount: 1,
    createdAt: '2026-07-25',
  },
];

export const INITIAL_CASES: ProcedureCase[] = [
  {
    id: 'case-2026-001',
    caseNumber: 'EXP-2026-0089',
    title: 'Transferencia por Sucesión - Fiat Cronos (Demo)',
    clientId: 'cli-102',
    clientName: 'Cliente Demo Persona',
    clientDniCuit: '20-00000002-4',
    vehicleDomain: 'AF123JK',
    vehicleBrandModel: 'Fiat Cronos Precision 1.8 2022',
    procedureId: 'proc-transferencia-fallecimiento',
    procedureTitle: 'Transferencia por Fallecimiento (Sucesión)',
    status: 'EN_PROCESO',
    checklist: [
      { id: 'chk-1', title: 'Oficio Judicial / Testimonio de Sucesión', isRequired: true, isCompleted: true },
      { id: 'chk-2', title: 'Declaratoria de Herederos en copias certificadas', isRequired: true, isCompleted: true },
      { id: 'chk-3', title: 'Solicitud Tipo 08 firmado por herederos', isRequired: true, isCompleted: false },
      { id: 'chk-4', title: 'Verificación Policial Formulario 12', isRequired: true, isCompleted: true },
      { id: 'chk-5', title: 'Informe de Dominio e Inhibiciones', isRequired: false, isCompleted: true },
    ],
    uploadedDocs: [],
    notes: [
      { id: 'n-1', author: 'Dr. Demo', text: 'Se recibió testimonio del Juzgado Demo.', date: '2026-08-02' },
      { id: 'n-2', author: 'Mandatario Demo', text: 'Pendiente firma de Solicitud 08.', date: '2026-08-05' },
    ],
    turnsDate: '2026-08-18 10:30',
    feesAmount: 145000,
    feesPaid: true,
    createdAt: '2026-07-28',
    updatedAt: '2026-08-05',
  },
  {
    id: 'case-2026-002',
    caseNumber: 'EXP-2026-0094',
    title: 'Transferencia Soc. Anon. - Toyota Hilux (Demo)',
    clientId: 'cli-101',
    clientName: 'Cliente Empresa Demo S.A.',
    clientDniCuit: '30-00000000-1',
    vehicleDomain: 'AC892PQ',
    vehicleBrandModel: 'Toyota Hilux SRX 4x4 2020',
    procedureId: 'proc-transferencia-persona-juridica',
    procedureTitle: 'Transferencia con Persona Jurídica (Empresa)',
    status: 'DOC_INCOMPLETA',
    checklist: [
      { id: 'chk-10', title: 'Estatuto Social inscripto en IGJ', isRequired: true, isCompleted: true },
      { id: 'chk-11', title: 'Acta de Asamblea de designación de autoridades', isRequired: true, isCompleted: false },
      { id: 'chk-12', title: 'Solicitud 08 firmado por representantes legales', isRequired: true, isCompleted: false },
      { id: 'chk-13', title: 'Formulario 12 Verificación Policial', isRequired: true, isCompleted: true },
    ],
    uploadedDocs: [],
    notes: [
      { id: 'n-10', author: 'Asistente Demo', text: 'Se requirió la última acta de directorio.', date: '2026-08-08' },
    ],
    turnsDate: '2026-08-22 11:15',
    feesAmount: 210000,
    feesPaid: false,
    createdAt: '2026-08-01',
    updatedAt: '2026-08-08',
  },
];

